### PR TITLE
AntD update, EditTabs component, code maintenance and some new features

### PR DESCRIPTION
**Pull request by Nigogu**
Please test and review when possible to merge and deploy. Thanks!

### CODE REVIEW

**Review by adcorredorm — CHANGES_REQUESTED** [review]
Hey there, this is a really good job, but can you check this little details?
- Don't show committee's response, just mark if it exist or not (if its different from "En Espera")
- Put a * to case type as mandatory field
- Check if the table fields uses the default value that is sent (I'm going to check if all of this return a not null default value :P)

**Comment by Nigogu** [comment]
Thanks for your review! 

The first two things were pretty simple and fixed in the latest commit. About the third thing, in fact, EditTabs is now properly displaying the default values from the backend's /infocase route response (previously, in EditTable, it was using the display value as default, which can cause problems like setting an incorrect datatype).

If we want to set default values, they sould be given in each field's default from /infocase response. Here is an example with CAIM. Tipology and credits have default values and the fields are filled when a new tab is added:

image
image

**Comment by Nigogu** [comment]
Secretary fixes requested were added in the latest commit.

**Review by adcorredorm — APPROVED** [review]
Good job :+1:

**Pull request merged**
